services:
  # ==========================================
  # [WEB] WORDPRESS CONTAINER (OPENLITESPEED)
  # ==========================================
  wordpress:
    build:
      context: .
    container_name: ${PROJECT_NAME}_wp
    shm_size: '1gb'
    ports:
      - "${APP_PORT}:80"
      - "${OLS_ADMIN_PORT}:7080"
    deploy:
      resources:
        limits:
          memory: 2048M
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./lsws/${PROJECT_NAME}:/usr/local/lsws/${PROJECT_NAME}
      - .:/var/www/vhosts/localhost/html
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=wp_shared_net"
    networks:
      - wp_net
      - wp_shared_net
    depends_on:
      - db
      - redis

  # ==========================================
  # [DB] MARIADB CONTAINER
  # ==========================================
  db:
    image: mariadb:10.11
    container_name: ${PROJECT_NAME}_db
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net

  # ==========================================
  # [CACHE] REDIS
  # ==========================================
  redis:
    image: redis:6-alpine
    container_name: ${PROJECT_NAME}_redis
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped
    networks:
      - wp_net

networks:
  wp_net:
    internal: true
    ipam:
      config:
        - subnet: ${SUBNET:-172.20.0.0/24}
  wp_shared_net:
    external: true

volumes:
  db_data:
